# NUMPY


In [1]:
import numpy as np

**THE BASICS**

In [2]:
a = np.array([1,2,3], dtype = 'int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get type
a.dtype

dtype('int32')

In [7]:
# Get number of elements
a.size

3

In [8]:
# Get size
a.nbytes

12

**ACCESSING/CHANGING SPECEFIC ELEMENTS, ROWS, COLUNNS ETC.**

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get a specefic element
a[1,1]

9

In [11]:
# Get a specefic row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specefic column
a[:,5]

array([ 6, 13])

In [13]:
# Getting a little more fancy [start:end:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [14]:
# To change elements
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3D example

In [15]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# Get specefic element (Works outside in)
b[1,0,0]

5

In [17]:
# Replace
b[1,0,0] = 1000
print(b)

[[[   1    2]
  [   3    4]]

 [[1000    6]
  [   7    8]]]


In [18]:
# Replace advanced
b[0,1,:] = [44444,5555]
print(b)

[[[    1     2]
  [44444  5555]]

 [[ 1000     6]
  [    7     8]]]


**INITIALIZE AN ARRAY**

In [19]:
# All zeroes
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# All ones 
np.ones((3,3), dtype = 'int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
# Any other number
np.full((3,3), 123)

array([[123, 123, 123],
       [123, 123, 123],
       [123, 123, 123]])

In [22]:
# Any other number (full_like)-uses a previous array for shape
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [23]:
# Random decimal number
np.random.rand(4,2)

array([[0.66581759, 0.55243347],
       [0.85448861, 0.15330735],
       [0.91904175, 0.28899117],
       [0.65409567, 0.95415885]])

In [24]:
# Random integer values
np.random.randint(-3,7, size=(3,3))

array([[ 0,  4,  0],
       [ 6, -2,  6],
       [-1, -3,  0]])

In [25]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

***CHALLENGE***

In [26]:
output = np.ones((5,5), int)
z = np.zeros((3,3), int)
output[1:-1, 1:-1] = z
output[2,2] = 9
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Be careful when copying array!!!

In [27]:
# Wrong way (as this changes the main value)
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [28]:
# CORRECT WAY TO COPY
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


## MATHEMATICS

In [29]:
math = np.array([1,2,3,4])

In [30]:
print(math)

[1 2 3 4]


In [31]:
math + 2

array([3, 4, 5, 6])

In [32]:
math - 2

array([-1,  0,  1,  2])

In [33]:
math * 2

array([2, 4, 6, 8])

In [34]:
math / 2

array([0.5, 1. , 1.5, 2. ])

In [35]:
math // 2

array([0, 1, 1, 2], dtype=int32)

In [36]:
# Trigonometry
np.tan(math)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

##### LINEAR ALGEBRA

In [37]:
a = np.full((2,3),1)

b = np.full((3,2), 2 )
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [38]:
# FIND THE DETERMINANT
c = np.identity(3)
np.linalg.det(c)

1.0

##### STATISTICS

In [39]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.min(stats)

1

In [41]:
np.max(stats)

6

In [42]:
np.max(stats, axis=0)

array([4, 5, 6])

In [43]:
np.sum(stats, axis=0)

array([5, 7, 9])

##### REORGANIZING ARRAYS

In [44]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [45]:
# VERTICALLY STACKING VECTORS
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [46]:
# HORIZONTALLY STACKING VECTOR
h1 = np.ones((2,3))
h2 = np.zeros((2,2))

np.hstack([h1,h2,h1])

array([[1., 1., 1., 0., 0., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1.]])

# MISCELLANEOUS


***LOAD DATA FROM FILE***

In [47]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

##### BOOLEAN MASKING AND ADVANCED INDEXING

In [48]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [49]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [50]:
## We can index with a list in NumPY - Access elements like in a list
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [51]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [52]:
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [53]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [54]:
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

###### quiz 

In [55]:
question = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]]) 
print(question)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [56]:
# Q1) Access the elements 11,12,16,17
question[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [57]:
question[[]]

array([], shape=(0, 5), dtype=int32)

In [58]:
# Q1) Access the elements 2 8 14 20
question[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [59]:
# Q1) Access the elements 4 5 24 25 29 30
question[[0,4,5],3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])