In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
a[1,3]

11

In [4]:
a[:,3]

array([ 4, 11])

In [5]:
a[1,1:6:2]

array([ 9, 11, 13])

In [6]:
a[0,5] = 100
print(a)

[[  1   2   3   4   5 100   7]
 [  8   9  10  11  12  13  14]]


In [7]:
a[:,6] = [1111,2222]
print(a)

[[   1    2    3    4    5  100 1111]
 [   8    9   10   11   12   13 2222]]


In [8]:
np.full((4,4), 404)

array([[404, 404, 404, 404],
       [404, 404, 404, 404],
       [404, 404, 404, 404],
       [404, 404, 404, 404]])

In [9]:
np.identity(5,dtype='int64')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [10]:
np.full_like(a, 911)

array([[911, 911, 911, 911, 911, 911, 911],
       [911, 911, 911, 911, 911, 911, 911]])

In [24]:
a= np.ones((5,5), int)
z = np.zeros((3,3), int)
a[1:4,1:4] = z
a[2,2] = 9
print(a)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [25]:
question = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]]) 
print(question)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [26]:
question[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [29]:
question[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [33]:
question[[0,4,5],3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])